version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of your dependencies
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "example-package"
        versions:
          - "1.x"