#client.rest

#gets all orders for the client_id
Get http://localhost:3000/api/v1/clients/1/orders
API_KEY : a1b2c3d4e5
Content-Type: application/json
#Error 404; not found

#suppliers.rest

#gets all items for a supplier
Get http://localhost:3000/api/v1/suppliers/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
#Error 404; not found

#shipment.rest

#gets all orders in a shipment
Get http://localhost:3000/api/v1/shipments/1/orders
API_KEY : a1b2c3d4e5
Content-Type: application/json 
#Error 404; not found

### gets all items in a shipment
Get http://localhost:3000/api/v1/orders/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
# gebruikt niet de juiste function in de model; 
# get_items_in_shipment maar iets anders??


#inventories.rest
### gets an inventories based on id 1
Get http://localhost:3000/api/v1/inventories/731
API_KEY : a1b2c3d4e5
Content-Type: application/json
#error 404; not found