#shipment.rest
### gets all items in a shipment
Get http://localhost:3000/api/v1/orders/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
# gebruikt niet de juiste function in de model; 
# get_items_in_shipment maar iets anders??
# update; nu gefixt maar weet niet waarom :)

#items.rest
### gets all inventories for an item
Get http://localhost:3000/api/v1/items/P000001/inventory
API_KEY : a1b2c3d4e5
Content-Type: application/json
#500 Internal Server Error

#client.rest
### gets all orders for the client_id
Get http://localhost:3000/api/v1/clients/1/orders
API_KEY : a1b2c3d4e5
Content-Type: application/json
#Error 404; not found

#suppliers.rest
### gets all items for a supplier
Get http://localhost:3000/api/v1/suppliers/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
#Error 404; not found

#shipment.rest
### gets all orders in a shipment
Get http://localhost:3000/api/v1/shipments/1/orders
API_KEY : a1b2c3d4e5
Content-Type: application/json 
#Error 404; not found

#inventories.rest
### gets an inventories based on id 1
Get http://localhost:3000/api/v1/inventories/731
API_KEY : a1b2c3d4e5
Content-Type: application/json
#error 404; not found

#item_groups.rest
### gets all items in the item_group
Get http://localhost:3000/api/v1/item_groups/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
#error 404; not found

#item_lines.rest
### gets all items in the item_line
Get http://localhost:3000/api/v1/item_lines/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
#error 404; not found

#item_types.rest
### gets all items in the item_type
Get http://localhost:3000/api/v1/item_types/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
#error 404; not found