########## GET ENDPOINTS ##########

### gets all shipments
Get http://localhost:3000/api/v1/shipments
API_KEY : a1b2c3d4e5
Content-Type: application/json
###

### gets a shipment based on id 1
Get http://localhost:3000/api/v1/shipments/2
API_KEY : a1b2c3d4e5
Content-Type: application/json
###

### gets all orders in a shipment
Get http://localhost:3000/api/v1/shipments/1/orders
API_KEY : a1b2c3d4e5
Content-Type: application/json
###

### gets all items in a shipment
Get http://localhost:3000/api/v1/orders/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json
###





########## PUT ENDPOINTS ##########

### updates a shipment based on id 1
PUT http://localhost:3000/api/v1/shipments/1
API_KEY : a1b2c3d4e5
Content-Type: application/json

{
    "id": 1,
    "order_id": 1,
    "source_id": 33,
    "order_date": "2000-03-09",
    "request_date": "2000-03-11",
    "shipment_date": "2000-03-13",
    "shipment_type": "I",
    "shipment_status": "Pending",
    "notes": "Zee vertrouwen klas rots heet lachen oneven begrijpen.",
    "carrier_code": "DPD",
    "carrier_description": "Dynamic Parcel Distribution",
    "service_code": "Fastest",
    "payment_type": "Manual",
    "transfer_mode": "Ground",
    "total_package_count": 31,
    "total_package_weight": 594.42,
    "created_at": "2000-03-10T11:11:14Z",
    "updated_at": "2000-03-11T13:11:14Z",
    "items": [
        {
            "item_id": "P007435",
            "amount": 23
        },
        {
            "item_id": "P009557",
            "amount": 1
        },
        {
            "item_id": "P009553",
            "amount": 50
        },
        {
            "item_id": "P010015",
            "amount": 16
        },
        {
            "item_id": "P002084",
            "amount": 33
        },
        {
            "item_id": "P009663",
            "amount": 18
        },
        {
            "item_id": "P010125",
            "amount": 18
        },
        {
            "item_id": "P005768",
            "amount": 26
        },
        {
            "item_id": "P004051",
            "amount": 1
        },
        {
            "item_id": "P005026",
            "amount": 29
        },
        {
            "item_id": "P000726",
            "amount": 22
        },
        {
            "item_id": "P008107",
            "amount": 47
        },
        {
            "item_id": "P001598",
            "amount": 32
        },
        {
            "item_id": "P002855",
            "amount": 20
        },
        {
            "item_id": "P010404",
            "amount": 30
        },
        {
            "item_id": "P010446",
            "amount": 6
        },
        {
            "item_id": "P001517",
            "amount": 9
        },
        {
            "item_id": "P009265",
            "amount": 2
        },
        {
            "item_id": "P001108",
            "amount": 20
        },
        {
            "item_id": "P009110",
            "amount": 18
        },
        {
            "item_id": "P009686",
            "amount": 13
        }
    ]
}
###

### updates the orders in a shipment based on id 1
PUT http://localhost:3000/api/v1/shipments/1/orders
API_KEY : a1b2c3d4e5
Content-Type: application/json

[1]
###

### updates the items in a shipment based on id 1
PUT http://localhost:3000/api/v1/shipments/1/items
API_KEY : a1b2c3d4e5
Content-Type: application/json

[
    {
        "item_id": "P007435",
        "amount": 23
    },
    {
        "item_id": "P009557",
        "amount": 1
    },
    {
        "item_id": "P009553",
        "amount": 50
    },
    {
        "item_id": "P010015",
        "amount": 16
    },
    {
        "item_id": "P002084",
        "amount": 33
    },
    {
        "item_id": "P009663",
        "amount": 18
    },
    {
        "item_id": "P010125",
        "amount": 18
    },
    {
        "item_id": "P005768",
        "amount": 26
    },
    {
        "item_id": "P004051",
        "amount": 1
    },
    {
        "item_id": "P005026",
        "amount": 29
    },
    {
        "item_id": "P000726",
        "amount": 22
    },
    {
        "item_id": "P008107",
        "amount": 47
    },
    {
        "item_id": "P001598",
        "amount": 32
    },
    {
        "item_id": "P002855",
        "amount": 20
    },
    {
        "item_id": "P010404",
        "amount": 30
    },
    {
        "item_id": "P010446",
        "amount": 6
    },
    {
        "item_id": "P001517",
        "amount": 9
    },
    {
        "item_id": "P009265",
        "amount": 2
    },
    {
        "item_id": "P001108",
        "amount": 20
    },
    {
        "item_id": "P009110",
        "amount": 18
    },
    {
        "item_id": "P009686",
        "amount": 13
    }
]

###

### activates the shipment, it updates the inventories for all items inside the shipment 
PUT http://localhost:3000/api/v1/shipments/1/commit
API_KEY : a1b2c3d4e5
Content-Type: application/json
###





########## POST ENDPOINTS ##########

### adds a new shipment to database
POST http://localhost:3000/api/v1/shipments
API_KEY : a1b2c3d4e5
Content-Type: application/json

{
    "id": 1,
    "order_id": 1,
    "source_id": 33,
    "order_date": "2000-03-09",
    "request_date": "2000-03-11",
    "shipment_date": "2000-03-13",
    "shipment_type": "I",
    "shipment_status": "Pending",
    "notes": "Zee vertrouwen klas rots heet lachen oneven begrijpen.",
    "carrier_code": "DPD",
    "carrier_description": "Dynamic Parcel Distribution",
    "service_code": "Fastest",
    "payment_type": "Manual",
    "transfer_mode": "Ground",
    "total_package_count": 31,
    "total_package_weight": 594.42,
    "created_at": "2000-03-10T11:11:14Z",
    "updated_at": "2000-03-11T13:11:14Z",
    "items": [
        {
            "item_id": "P007435",
            "amount": 23
        },
        {
            "item_id": "P009557",
            "amount": 1
        },
        {
            "item_id": "P009553",
            "amount": 50
        },
        {
            "item_id": "P010015",
            "amount": 16
        },
        {
            "item_id": "P002084",
            "amount": 33
        },
        {
            "item_id": "P009663",
            "amount": 18
        },
        {
            "item_id": "P010125",
            "amount": 18
        },
        {
            "item_id": "P005768",
            "amount": 26
        },
        {
            "item_id": "P004051",
            "amount": 1
        },
        {
            "item_id": "P005026",
            "amount": 29
        },
        {
            "item_id": "P000726",
            "amount": 22
        },
        {
            "item_id": "P008107",
            "amount": 47
        },
        {
            "item_id": "P001598",
            "amount": 32
        },
        {
            "item_id": "P002855",
            "amount": 20
        },
        {
            "item_id": "P010404",
            "amount": 30
        },
        {
            "item_id": "P010446",
            "amount": 6
        },
        {
            "item_id": "P001517",
            "amount": 9
        },
        {
            "item_id": "P009265",
            "amount": 2
        },
        {
            "item_id": "P001108",
            "amount": 20
        },
        {
            "item_id": "P009110",
            "amount": 18
        },
        {
            "item_id": "P009686",
            "amount": 13
        }
    ]
}
###





########## DELETE ENDPOINTS ##########

### removes a shipment based on id 1
DELETE http://localhost:3000/api/v1/shipments/1
API_KEY : a1b2c3d4e5
###



### Marked Wrong Endpoints ###
# The POST and PUT endpoints accept incomplete, resulting in inconsistent data in the json
# The POST and PUT endpoints accepts existing id's, leading to double id's
# The GET, PUT and DELETE endpoint accepts nonexistent id's 

# The PUT order update returns 200 OK, but can cause negative id's and potentially more errors
# The PUT item update does not work
# The PUT commit endpoint does not work