# gets all warehouses
Get http://localhost:3000/api/v1/warehouses
API_KEY : a1b2c3d4e5
Content-Type: application/json
###

# gets a specific warehouse based on id
Get http://localhost:3000/api/v1/warehouses/1
API_KEY : a1b2c3d4e5
Content-Type: application/json
###


# gets all locations of warehouse with id 2
# return list of all shelves of warehouse with id 2
Get http://localhost:3000/api/v1/warehouses/2/locations
API_KEY : a1b2c3d4e5
Content-Type: application/json

###