name: Python Test Coverage and Performance

on:
  push:
    branches:
      - main
      - Development-Branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run performance tests with coverage
        run: |
          cd api/Tests
          cd "performance tests"
          python performance_async_multiple
          python performance_async
          python performance_threads_multiple
          python performance
        env:
          API_KEY_1: ${{ secrets.API_KEY_1 }}
          API_KEY_2: ${{ secrets.API_KEY_2 }}

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
