name: Main and pytest test

on:
  push:
    branches: 
      - main
      - Development-Branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure test data is present
      run: |
        if [ ! -d "api/Tests/Test_Data" ]; then
          echo "Test_Data folder is missing!"
          exit 1
        fi
        ls api/Tests/Test_Data

    - name: Start server
      run: |
        nohup python api/main.py &
        sleep 10
      env:
        API_KEY_1: a1b2c3d4e5
        API_KEY_2: f6g7h8i9j0

    - name: Run tests
      run: |
        cd api/Tests
        pytest
      env:
        API_KEY_1: a1b2c3d4e5
        API_KEY_2: f6g7h8i9j0