name: Python Performance Test

on:
  push:
    branches:
      - main
      - Development-Branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run performance.py
        run: |
          pkill -f "python api/main.py" || true
          nohup python api/main.py &
          sleep 10
          python "api/Tests/Performance Tests/performance.py"
          pkill -f "python api/main.py" || true
        env:
          API_KEY_1: ${{ secrets.API_KEY_1 }}
          API_KEY_2: ${{ secrets.API_KEY_2 }}

      - name: Run performance_async.py
        run: |
          python api/cargohub_db.py
          pkill -f "python api/main.py" || true
          nohup python api/main.py &
          sleep 10
          python "api/Tests/Performance Tests/performance_async.py"
          pkill -f "python api/main.py" || true
        env:
          API_KEY_1: ${{ secrets.API_KEY_1 }}
          API_KEY_2: ${{ secrets.API_KEY_2 }}

      - name: Run performance_async_multiple.py
        run: |
          python api/cargohub_db.py
          pkill -f "python api/main.py" || true
          nohup python api/main.py &
          sleep 10
          python "api/Tests/Performance Tests/performance_async_multiple.py"
          pkill -f "python api/main.py" || true
        env:
          API_KEY_1: ${{ secrets.API_KEY_1 }}
          API_KEY_2: ${{ secrets.API_KEY_2 }}

      - name: Run performance_threads_multiple.py
        run: |
          python api/cargohub_db.py
          pkill -f "python api/main.py" || true
          nohup python api/main.py &
          sleep 10
          python "api/Tests/Performance Tests/performance_threads_multiple.py"
          pkill -f "python api/main.py" || true
        env:
          API_KEY_1: ${{ secrets.API_KEY_1 }}
          API_KEY_2: ${{ secrets.API_KEY_2 }}