name: Python executing pytest on all unittest

on:
  push:
    branches: 
      - main
      - Development-Branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run cargohub_db.py to create test database
      run: |
        python api/cargohub_db.py
        sleep 20
    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check cargohub_test.db existence
      run: |
        if [ ! -f "api/Tests/Test_Data/Cargohub_Test.db" ]; then
          echo "cargohub_test.db is missing!"
          exit 1
        else
          echo "cargohub_test.db exists."
        fi
    # - name: Start server
    #   run: |
    #     nohup python api/main.py & 
    #     sleep 20
    #   env:
    #     API_KEY_1: ${{ secrets.API_KEY_1 }}
    #     API_KEY_2: ${{ secrets.API_KEY_2 }}
    - name: Run tests
      run: |
        cd api/Tests/unit
        pytest
      env:
        API_KEY_1: ${{ secrets.API_KEY_1 }}
        API_KEY_2: ${{ secrets.API_KEY_2 }}
